name: Lint
on: [pull_request]
jobs:
  pssa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -RequiredVersion 1.24.0 -Force -Scope CurrentUser
          $r = Invoke-ScriptAnalyzer -Path ./EntraVacuum -Recurse `
            -Severity Error, Warning `
            -ExcludeRule "PSUseBOMForUnicodeEncodedFile", "PSMissingModuleManifestField"
          $r | Format-Table
          if ($r) { exit 1 }
